using Naswood.Modules.Platform.Domain.Authorization;

namespace Naswood.Modules.Platform.Application.Authorization;

/// <summary>
/// Seeds the permission catalog and Administrator role from approved design samples.
/// Mutation APIs remain TASK-004 / TASK-005.
/// </summary>
public static class AuthorizationCatalogSeed
{
    public static IReadOnlyList<PermissionDefinition> CreatePermissions()
    {
        var specs = new (string Code, string Module, string? Entity, string Action, string? Field, string Name)[]
        {
            ("Platform.Dashboard.View", "Platform", "Dashboard", "View", null, "View Dashboard"),
            ("Authorization.View", "Authorization", null, "View", null, "View Authorization"),
            ("Authorization.Configure", "Authorization", null, "Configure", null, "Configure Authorization"),
            ("Authorization.Assign", "Authorization", null, "Assign", null, "Assign Authorization"),
            ("Authorization.Export", "Authorization", null, "Export", null, "Export Authorization"),
            ("Authorization.Audit", "Authorization", null, "Audit", null, "Audit Authorization"),
            ("Administration.Manage", "Administration", null, "Manage", null, "Manage Administration"),
            ("Administration.User.Delete", "Administration", "User", "Delete", null, "Delete User"),
            ("User.View", "Administration", "User", "View", null, "View User"),
            ("User.Create", "Administration", "User", "Create", null, "Create User"),
            ("User.Update", "Administration", "User", "Update", null, "Update User"),
            ("User.Delete", "Administration", "User", "Delete", null, "Delete User"),
            ("User.Export", "Administration", "User", "Export", null, "Export User"),
            ("User.Import", "Administration", "User", "Import", null, "Import User"),
            ("User.AssignRole", "Administration", "User", "AssignRole", null, "Assign User Role"),
            ("User.ResetPassword", "Administration", "User", "ResetPassword", null, "Reset User Password"),
            ("User.Lock", "Administration", "User", "Lock", null, "Lock User"),
            ("User.Unlock", "Administration", "User", "Unlock", null, "Unlock User"),
            ("Role.View", "Administration", "Role", "View", null, "View Role"),
            ("Role.Create", "Administration", "Role", "Create", null, "Create Role"),
            ("Role.Update", "Administration", "Role", "Update", null, "Update Role"),
            ("Role.Delete", "Administration", "Role", "Delete", null, "Delete Role"),
            ("Role.Assign", "Administration", "Role", "Assign", null, "Assign Role"),
            ("Role.Export", "Administration", "Role", "Export", null, "Export Role"),
            ("Role.Import", "Administration", "Role", "Import", null, "Import Role"),
            ("Role.Clone", "Administration", "Role", "Clone", null, "Clone Role"),
            ("Role.Configure", "Administration", "Role", "Configure", null, "Configure Role"),
            ("Permission.View", "Administration", "Permission", "View", null, "View Permission"),
            ("Permission.Create", "Administration", "Permission", "Create", null, "Create Permission"),
            ("Permission.Update", "Administration", "Permission", "Update", null, "Update Permission"),
            ("Permission.Delete", "Administration", "Permission", "Delete", null, "Delete Permission"),
            ("Permission.Export", "Administration", "Permission", "Export", null, "Export Permission"),
            ("Permission.Import", "Administration", "Permission", "Import", null, "Import Permission"),
            ("Permission.Assign", "Administration", "Permission", "Assign", null, "Assign Permission"),
            ("Permission.Configure", "Administration", "Permission", "Configure", null, "Configure Permission"),
            ("Audit.View", "Administration", "Audit", "View", null, "View Audit"),
            ("Audit.Export", "Administration", "Audit", "Export", null, "Export Audit"),
            ("Audit.Archive", "Administration", "Audit", "Archive", null, "Archive Audit"),
            ("Audit.Retention", "Administration", "Audit", "Retention", null, "Audit Retention"),
            ("Audit.Configuration", "Administration", "Audit", "Configuration", null, "Audit Configuration"),
            ("Settings.View", "Administration", "Settings", "View", null, "View Settings"),
            ("Settings.Create", "Administration", "Settings", "Create", null, "Create Settings"),
            ("Settings.Update", "Administration", "Settings", "Update", null, "Update Settings"),
            ("Settings.Delete", "Administration", "Settings", "Delete", null, "Delete Settings"),
            ("Settings.Export", "Administration", "Settings", "Export", null, "Export Settings"),
            ("Settings.Import", "Administration", "Settings", "Import", null, "Import Settings"),
            ("Settings.Restore", "Administration", "Settings", "Restore", null, "Restore Settings"),
            ("Settings.Configure", "Administration", "Settings", "Configure", null, "Configure Settings"),
            ("File.View", "Administration", "File", "View", null, "View File"),
            ("File.Upload", "Administration", "File", "Upload", null, "Upload File"),
            ("File.Download", "Administration", "File", "Download", null, "Download File"),
            ("File.Delete", "Administration", "File", "Delete", null, "Delete File"),
            ("File.Restore", "Administration", "File", "Restore", null, "Restore File"),
            ("File.Version", "Administration", "File", "Version", null, "Version File"),
            ("Material.View", "Inventory", "Material", "View", null, "View Material"),
            ("Material.Create", "Inventory", "Material", "Create", null, "Create Material"),
            ("Material.Update", "Inventory", "Material", "Update", null, "Update Material"),
            ("Material.Delete", "Inventory", "Material", "Delete", null, "Delete Material"),
            ("Warehouse.View", "Inventory", "Warehouse", "View", null, "View Warehouse"),
            ("Warehouse.Create", "Inventory", "Warehouse", "Create", null, "Create Warehouse"),
            ("Warehouse.Update", "Inventory", "Warehouse", "Update", null, "Update Warehouse"),
            ("Warehouse.Delete", "Inventory", "Warehouse", "Delete", null, "Delete Warehouse"),
            ("Location.View", "Inventory", "Location", "View", null, "View Location"),
            ("Location.Create", "Inventory", "Location", "Create", null, "Create Location"),
            ("Location.Update", "Inventory", "Location", "Update", null, "Update Location"),
            ("Location.Delete", "Inventory", "Location", "Delete", null, "Delete Location"),
            ("Inventory.View", "Inventory", "Inventory", "View", null, "View Inventory"),
            ("Inventory.Create", "Inventory", "Inventory", "Create", null, "Create Inventory"),
            ("Inventory.Update", "Inventory", "Inventory", "Update", null, "Update Inventory"),
            ("Inventory.Delete", "Inventory", "Inventory", "Delete", null, "Delete Inventory"),
            ("Batch.View", "Inventory", "Batch", "View", null, "View Batch"),
            ("Batch.Create", "Inventory", "Batch", "Create", null, "Create Batch"),
            ("Batch.Update", "Inventory", "Batch", "Update", null, "Update Batch"),
            ("Batch.Delete", "Inventory", "Batch", "Delete", null, "Delete Batch"),
            ("GoodsReceipt.View", "Inventory", "GoodsReceipt", "View", null, "View GoodsReceipt"),
            ("GoodsReceipt.Create", "Inventory", "GoodsReceipt", "Create", null, "Create GoodsReceipt"),
            ("GoodsReceipt.Update", "Inventory", "GoodsReceipt", "Update", null, "Update GoodsReceipt"),
            ("GoodsReceipt.Delete", "Inventory", "GoodsReceipt", "Delete", null, "Delete GoodsReceipt"),
            ("GoodsIssue.View", "Inventory", "GoodsIssue", "View", null, "View GoodsIssue"),
            ("GoodsIssue.Create", "Inventory", "GoodsIssue", "Create", null, "Create GoodsIssue"),
            ("GoodsIssue.Update", "Inventory", "GoodsIssue", "Update", null, "Update GoodsIssue"),
            ("GoodsIssue.Delete", "Inventory", "GoodsIssue", "Delete", null, "Delete GoodsIssue"),
            ("StockTransfer.View", "Inventory", "StockTransfer", "View", null, "View StockTransfer"),
            ("StockTransfer.Create", "Inventory", "StockTransfer", "Create", null, "Create StockTransfer"),
            ("StockTransfer.Update", "Inventory", "StockTransfer", "Update", null, "Update StockTransfer"),
            ("StockTransfer.Delete", "Inventory", "StockTransfer", "Delete", null, "Delete StockTransfer"),
            ("InventoryCount.View", "Inventory", "InventoryCount", "View", null, "View InventoryCount"),
            ("InventoryCount.Create", "Inventory", "InventoryCount", "Create", null, "Create InventoryCount"),
            ("InventoryCount.Update", "Inventory", "InventoryCount", "Update", null, "Update InventoryCount"),
            ("InventoryCount.Delete", "Inventory", "InventoryCount", "Delete", null, "Delete InventoryCount"),
            ("InventoryAdjustment.View", "Inventory", "InventoryAdjustment", "View", null, "View InventoryAdjustment"),
            ("InventoryAdjustment.Create", "Inventory", "InventoryAdjustment", "Create", null, "Create InventoryAdjustment"),
            ("InventoryAdjustment.Update", "Inventory", "InventoryAdjustment", "Update", null, "Update InventoryAdjustment"),
            ("InventoryAdjustment.Delete", "Inventory", "InventoryAdjustment", "Delete", null, "Delete InventoryAdjustment"),
            ("Supplier.View", "Purchasing", "Supplier", "View", null, "View Supplier"),
            ("Supplier.Create", "Purchasing", "Supplier", "Create", null, "Create Supplier"),
            ("Supplier.Update", "Purchasing", "Supplier", "Update", null, "Update Supplier"),
            ("Supplier.Delete", "Purchasing", "Supplier", "Delete", null, "Delete Supplier"),
            ("PurchaseRequest.View", "Purchasing", "PurchaseRequest", "View", null, "View PurchaseRequest"),
            ("PurchaseRequest.Create", "Purchasing", "PurchaseRequest", "Create", null, "Create PurchaseRequest"),
            ("PurchaseRequest.Update", "Purchasing", "PurchaseRequest", "Update", null, "Update PurchaseRequest"),
            ("PurchaseRequest.Delete", "Purchasing", "PurchaseRequest", "Delete", null, "Delete PurchaseRequest"),
            ("Rfq.View", "Purchasing", "Rfq", "View", null, "View Rfq"),
            ("Rfq.Create", "Purchasing", "Rfq", "Create", null, "Create Rfq"),
            ("Rfq.Update", "Purchasing", "Rfq", "Update", null, "Update Rfq"),
            ("Rfq.Delete", "Purchasing", "Rfq", "Delete", null, "Delete Rfq"),
            ("SupplierQuotation.View", "Purchasing", "SupplierQuotation", "View", null, "View SupplierQuotation"),
            ("SupplierQuotation.Create", "Purchasing", "SupplierQuotation", "Create", null, "Create SupplierQuotation"),
            ("SupplierQuotation.Update", "Purchasing", "SupplierQuotation", "Update", null, "Update SupplierQuotation"),
            ("SupplierQuotation.Delete", "Purchasing", "SupplierQuotation", "Delete", null, "Delete SupplierQuotation"),
            ("PurchaseOrder.View", "Purchasing", "PurchaseOrder", "View", null, "View PurchaseOrder"),
            ("PurchaseOrder.Create", "Purchasing", "PurchaseOrder", "Create", null, "Create PurchaseOrder"),
            ("PurchaseOrder.Update", "Purchasing", "PurchaseOrder", "Update", null, "Update PurchaseOrder"),
            ("PurchaseOrder.Delete", "Purchasing", "PurchaseOrder", "Delete", null, "Delete PurchaseOrder"),
            ("PurchaseGoodsReceipt.View", "Purchasing", "PurchaseGoodsReceipt", "View", null, "View PurchaseGoodsReceipt"),
            ("PurchaseGoodsReceipt.Create", "Purchasing", "PurchaseGoodsReceipt", "Create", null, "Create PurchaseGoodsReceipt"),
            ("PurchaseGoodsReceipt.Update", "Purchasing", "PurchaseGoodsReceipt", "Update", null, "Update PurchaseGoodsReceipt"),
            ("PurchaseGoodsReceipt.Delete", "Purchasing", "PurchaseGoodsReceipt", "Delete", null, "Delete PurchaseGoodsReceipt"),
            ("PurchaseReturn.View", "Purchasing", "PurchaseReturn", "View", null, "View PurchaseReturn"),
            ("PurchaseReturn.Create", "Purchasing", "PurchaseReturn", "Create", null, "Create PurchaseReturn"),
            ("PurchaseReturn.Update", "Purchasing", "PurchaseReturn", "Update", null, "Update PurchaseReturn"),
            ("PurchaseReturn.Delete", "Purchasing", "PurchaseReturn", "Delete", null, "Delete PurchaseReturn"),
            ("SupplierInvoice.View", "Purchasing", "SupplierInvoice", "View", null, "View SupplierInvoice"),
            ("SupplierInvoice.Create", "Purchasing", "SupplierInvoice", "Create", null, "Create SupplierInvoice"),
            ("SupplierInvoice.Update", "Purchasing", "SupplierInvoice", "Update", null, "Update SupplierInvoice"),
            ("SupplierInvoice.Delete", "Purchasing", "SupplierInvoice", "Delete", null, "Delete SupplierInvoice"),
            ("Purchasing.View", "Purchasing", null, "View", null, "View Purchasing"),
            ("PurchasingReport.View", "Purchasing", "PurchasingReport", "View", null, "View PurchasingReport"),
            ("PurchasingReport.Create", "Purchasing", "PurchasingReport", "Create", null, "Create PurchasingReport"),
            ("PurchasingReport.Update", "Purchasing", "PurchasingReport", "Update", null, "Update PurchasingReport"),
            ("PurchasingReport.Delete", "Purchasing", "PurchasingReport", "Delete", null, "Delete PurchasingReport"),
            ("Customer.View", "Sales", "Customer", "View", null, "View Customer"),
            ("Customer.Create", "Sales", "Customer", "Create", null, "Create Customer"),
            ("Customer.Update", "Sales", "Customer", "Update", null, "Update Customer"),
            ("Customer.Delete", "Sales", "Customer", "Delete", null, "Delete Customer"),
            ("Lead.View", "Sales", "Lead", "View", null, "View Lead"),
            ("Lead.Create", "Sales", "Lead", "Create", null, "Create Lead"),
            ("Lead.Update", "Sales", "Lead", "Update", null, "Update Lead"),
            ("Lead.Delete", "Sales", "Lead", "Delete", null, "Delete Lead"),
            ("Opportunity.View", "Sales", "Opportunity", "View", null, "View Opportunity"),
            ("Opportunity.Create", "Sales", "Opportunity", "Create", null, "Create Opportunity"),
            ("Opportunity.Update", "Sales", "Opportunity", "Update", null, "Update Opportunity"),
            ("Opportunity.Delete", "Sales", "Opportunity", "Delete", null, "Delete Opportunity"),
            ("SalesQuotation.View", "Sales", "SalesQuotation", "View", null, "View SalesQuotation"),
            ("SalesQuotation.Create", "Sales", "SalesQuotation", "Create", null, "Create SalesQuotation"),
            ("SalesQuotation.Update", "Sales", "SalesQuotation", "Update", null, "Update SalesQuotation"),
            ("SalesQuotation.Delete", "Sales", "SalesQuotation", "Delete", null, "Delete SalesQuotation"),
            ("SalesOrder.View", "Sales", "SalesOrder", "View", null, "View SalesOrder"),
            ("SalesOrder.Create", "Sales", "SalesOrder", "Create", null, "Create SalesOrder"),
            ("SalesOrder.Update", "Sales", "SalesOrder", "Update", null, "Update SalesOrder"),
            ("SalesOrder.Delete", "Sales", "SalesOrder", "Delete", null, "Delete SalesOrder"),
            ("Shipment.View", "Sales", "Shipment", "View", null, "View Shipment"),
            ("Shipment.Create", "Sales", "Shipment", "Create", null, "Create Shipment"),
            ("Shipment.Update", "Sales", "Shipment", "Update", null, "Update Shipment"),
            ("Shipment.Delete", "Sales", "Shipment", "Delete", null, "Delete Shipment"),
            ("Delivery.View", "Sales", "Delivery", "View", null, "View Delivery"),
            ("Delivery.Create", "Sales", "Delivery", "Create", null, "Create Delivery"),
            ("Delivery.Update", "Sales", "Delivery", "Update", null, "Update Delivery"),
            ("Delivery.Delete", "Sales", "Delivery", "Delete", null, "Delete Delivery"),
            ("CustomerInvoice.View", "Sales", "CustomerInvoice", "View", null, "View CustomerInvoice"),
            ("CustomerInvoice.Create", "Sales", "CustomerInvoice", "Create", null, "Create CustomerInvoice"),
            ("CustomerInvoice.Update", "Sales", "CustomerInvoice", "Update", null, "Update CustomerInvoice"),
            ("CustomerInvoice.Delete", "Sales", "CustomerInvoice", "Delete", null, "Delete CustomerInvoice"),
            ("Sales.View", "Sales", null, "View", null, "View Sales"),
            ("SalesReport.View", "Sales", "SalesReport", "View", null, "View SalesReport"),
            ("SalesReport.Create", "Sales", "SalesReport", "Create", null, "Create SalesReport"),
            ("SalesReport.Update", "Sales", "SalesReport", "Update", null, "Update SalesReport"),
            ("SalesReport.Delete", "Sales", "SalesReport", "Delete", null, "Delete SalesReport"),
            ("Bom.View", "Production", "Bom", "View", null, "View Bom"),
            ("Bom.Create", "Production", "Bom", "Create", null, "Create Bom"),
            ("Bom.Update", "Production", "Bom", "Update", null, "Update Bom"),
            ("Bom.Delete", "Production", "Bom", "Delete", null, "Delete Bom"),
            ("Routing.View", "Production", "Routing", "View", null, "View Routing"),
            ("Routing.Create", "Production", "Routing", "Create", null, "Create Routing"),
            ("Routing.Update", "Production", "Routing", "Update", null, "Update Routing"),
            ("Routing.Delete", "Production", "Routing", "Delete", null, "Delete Routing"),
            ("Machine.View", "Production", "Machine", "View", null, "View Machine"),
            ("Machine.Create", "Production", "Machine", "Create", null, "Create Machine"),
            ("Machine.Update", "Production", "Machine", "Update", null, "Update Machine"),
            ("Machine.Delete", "Production", "Machine", "Delete", null, "Delete Machine"),
            ("WorkCenter.View", "Production", "WorkCenter", "View", null, "View WorkCenter"),
            ("WorkCenter.Create", "Production", "WorkCenter", "Create", null, "Create WorkCenter"),
            ("WorkCenter.Update", "Production", "WorkCenter", "Update", null, "Update WorkCenter"),
            ("WorkCenter.Delete", "Production", "WorkCenter", "Delete", null, "Delete WorkCenter"),
            ("ProductionLine.View", "Production", "ProductionLine", "View", null, "View ProductionLine"),
            ("ProductionLine.Create", "Production", "ProductionLine", "Create", null, "Create ProductionLine"),
            ("ProductionLine.Update", "Production", "ProductionLine", "Update", null, "Update ProductionLine"),
            ("ProductionLine.Delete", "Production", "ProductionLine", "Delete", null, "Delete ProductionLine"),
            ("Inventory.Export", "Inventory", null, "Export", null, "Export Inventory"),
            ("Inventory.Import", "Inventory", null, "Import", null, "Import Inventory"),
            ("GoodsReceipt.Execute", "Inventory", "GoodsReceipt", "Execute", null, "Execute Goods Receipt"),
            ("GoodsIssue.Execute", "Inventory", "GoodsIssue", "Execute", null, "Execute Goods Issue"),
            ("PurchaseOrder.Approve", "Purchasing", "PurchaseOrder", "Approve", null, "Approve Purchase Order"),
            ("PurchaseOrder.Price.View", "Purchasing", "PurchaseOrder", "View", "Price", "View Purchase Order Price"),
            ("PurchaseOrder.Own", "Purchasing", "PurchaseOrder", "Own", null, "Own Purchase Order Access"),
            ("SalesOrder.Approve", "Sales", "SalesOrder", "Approve", null, "Approve Sales Order"),
            ("Production.View", "Production", null, "View", null, "View Production"),
            ("ProductionOrder.Approve", "Production", "ProductionOrder", "Approve", null, "Approve Production Order"),
            ("Quality.View", "Quality", null, "View", null, "View Quality"),
            ("QualityInspection.Execute", "Quality", "QualityInspection", "Execute", null, "Execute Quality Inspection"),
            ("Maintenance.View", "Maintenance", null, "View", null, "View Maintenance"),
            ("MaintenanceOrder.Execute", "Maintenance", "MaintenanceOrder", "Execute", null, "Execute Maintenance Order"),
            ("Finance.View", "Finance", null, "View", null, "View Finance"),
            ("Finance.Report.View", "Finance", "Report", "View", null, "View Finance Report"),
            ("AI.Chat", "AI", null, "Chat", null, "Use AI Chat")
        };

        return specs
            .Select(s => PermissionDefinition.Create(s.Code, s.Module, s.Action, s.Name, s.Entity, s.Field))
            .ToArray();
    }

    public static RoleDefinition CreateAdministratorRole(IEnumerable<PermissionDefinition> permissions) =>
        RoleDefinition.Create(
            "Administrator",
            "Administrator",
            permissions.Select(p => p.Code));

    public static RoleDefinition CreateReadOnlyRole() =>
        RoleDefinition.Create(
            "ReadOnly",
            "Read Only",
            [
                "Platform.Dashboard.View",
                "Authorization.View",
                "Inventory.View",
                "Warehouse.View",
                "Purchasing.View",
                "Sales.View",
                "Production.View",
                "Quality.View",
                "Maintenance.View",
                "Finance.View",
                "Finance.Report.View"
            ]);
}
