import { Link } from '@tanstack/react-router';
import { useState } from 'react';
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input } from '@naswood/ui';
import { useI18n } from '@/i18n';

export interface ProcessWizardStep {
  title: string;
  hint?: string;
  /** Business fields for this step (never Code/Number identifiers). */
  fields?: { key: string; label: string; type?: 'string' | 'number' | 'date'; placeholder?: string }[];
}

interface ProcessWizardProps {
  screenId: string;
  title: string;
  description: string;
  steps: ProcessWizardStep[];
  finishLabel: string;
  libraryPath: string;
  libraryLabel: string;
  /** e.g. MC-… BOM-… — shown as auto-generated, never editable */
  autoCodeHint?: string;
}

/** Job / Engineering shell — replaces shared Create forms. */
export function ProcessWizard({
  screenId,
  title,
  description,
  steps,
  finishLabel,
  libraryPath,
  libraryLabel,
  autoCodeHint,
}: ProcessWizardProps) {
  const { t } = useI18n();
  const [step, setStep] = useState(0);
  const [values, setValues] = useState<Record<string, string>>({});
  const [released, setReleased] = useState(false);
  const current = steps[step];
  const isLast = step >= steps.length - 1;
  const sampleCode = autoCodeHint
    ? `${autoCodeHint.replace(/…/g, '').replace(/\.\.\./g, '')}${String(100000 + (Object.keys(values).length + step) * 17).slice(-6)}`
    : null;

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-xs font-medium text-[var(--text-muted)]">{screenId}</p>
          <h2 className="text-xl font-semibold tracking-tight">{title}</h2>
          <p className="mt-1 text-sm text-[var(--text-secondary)]">{description}</p>
          <p className="mt-1 text-xs text-[var(--text-muted)]">{t('wizard.screenType')}</p>
        </div>
        <div className="flex flex-col items-end gap-2">
          {autoCodeHint ? (
            <div className="rounded-md border border-[var(--border-default)] bg-[var(--color-surface)] px-3 py-2 text-right">
              <p className="text-[10px] uppercase tracking-wide text-[var(--text-muted)]">{t('wizard.systemCode')}</p>
              <p className="font-mono text-sm font-medium text-[var(--text-primary)]">
                {released && sampleCode ? sampleCode : t('wizard.autoGenerated')}
              </p>
              <p className="text-[10px] text-[var(--text-muted)]">{autoCodeHint}</p>
            </div>
          ) : null}
          <Link to={libraryPath} className="text-sm font-medium text-[var(--color-primary)] hover:underline">
            {libraryLabel}
          </Link>
        </div>
      </div>

      <ol className="flex flex-wrap gap-2">
        {steps.map((s, i) => (
          <li key={s.title}>
            <button
              type="button"
              onClick={() => setStep(i)}
              className={`rounded-md px-3 py-1.5 text-xs font-medium ${
                i === step
                  ? 'bg-[var(--color-primary)] text-white'
                  : i < step
                    ? 'bg-[var(--color-surface-hover)] text-[var(--text-primary)]'
                    : 'bg-[var(--color-surface)] text-[var(--text-muted)]'
              }`}
            >
              {i + 1}. {s.title}
            </button>
          </li>
        ))}
      </ol>

      <Card>
        <CardHeader>
          <CardTitle>
            {step + 1}. {current?.title}
          </CardTitle>
          <CardDescription>{current?.hint ?? t('wizard.stepHint')}</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {current?.fields && current.fields.length > 0 ? (
            <div className="grid gap-3 md:grid-cols-2">
              {current.fields.map((f) => (
                <label key={f.key} className="space-y-1 text-sm">
                  <span className="text-[var(--text-secondary)]">{f.label}</span>
                  <Input
                    value={values[f.key] ?? ''}
                    type={f.type === 'number' ? 'number' : f.type === 'date' ? 'date' : 'text'}
                    placeholder={f.placeholder}
                    onChange={(e) => setValues((prev) => ({ ...prev, [f.key]: e.target.value }))}
                  />
                </label>
              ))}
            </div>
          ) : (
            <p className="text-sm text-[var(--text-secondary)]">{t('wizard.bodyHint')}</p>
          )}
          <div className="flex flex-wrap gap-2">
            <Button type="button" variant="secondary" disabled={step === 0} onClick={() => setStep((s) => s - 1)}>
              {t('wizard.back')}
            </Button>
            {!isLast ? (
              <Button type="button" onClick={() => setStep((s) => s + 1)}>
                {t('wizard.next')}
              </Button>
            ) : (
              <Button
                type="button"
                onClick={() => {
                  setReleased(true);
                }}
              >
                {finishLabel}
              </Button>
            )}
          </div>
          {released ? (
            <p className="text-sm font-medium text-[var(--color-primary)]">
              {t('wizard.releasedBanner')}
              {sampleCode ? ` · ${sampleCode}` : ''}
            </p>
          ) : null}
        </CardContent>
      </Card>
    </div>
  );
}
