import { Link, useNavigate } from '@tanstack/react-router';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input } from '@naswood/ui';
import { createResource } from '@/api/business';
import { useI18n } from '@/i18n';

export interface ProcessWizardStep {
  title: string;
  hint?: string;
  /** Business fields for this step (never Code/Number identifiers). */
  fields?: { key: string; label: string; type?: 'string' | 'number' | 'date'; placeholder?: string }[];
}

interface ProcessWizardProps {
  screenId: string;
  title: string;
  description: string;
  steps: ProcessWizardStep[];
  finishLabel: string;
  libraryPath: string;
  libraryLabel: string;
  /** e.g. MC-… BOM-… — shown as auto-generated, never editable */
  autoCodeHint?: string;
  /** When set, Release/Post persists via business API and appears in library */
  persistRoute?: string;
  /** Map wizard field values → API body (never include Code/Number — server mints) */
  mapBody?: (values: Record<string, string>) => Record<string, unknown>;
}

function readMintedCode(row: Record<string, unknown> | null | undefined): string | null {
  if (!row) return null;
  for (const key of ['code', 'number', 'batchNumber', 'Code', 'Number']) {
    const v = row[key];
    if (typeof v === 'string' && v.trim()) return v.trim();
  }
  return null;
}

/** Job / Engineering shell — replaces shared Create forms. Persists to library on finish. */
export function ProcessWizard({
  screenId,
  title,
  description,
  steps,
  finishLabel,
  libraryPath,
  libraryLabel,
  autoCodeHint,
  persistRoute,
  mapBody,
}: ProcessWizardProps) {
  const { t } = useI18n();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [step, setStep] = useState(0);
  const [values, setValues] = useState<Record<string, string>>({});
  const [released, setReleased] = useState(false);
  const [mintedCode, setMintedCode] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const current = steps[step];
  const isLast = step >= steps.length - 1;

  const persistMutation = useMutation({
    mutationFn: async () => {
      if (!persistRoute || !mapBody) {
        throw new Error('persistRoute/mapBody required');
      }
      const body = mapBody(values);
      return createResource<Record<string, unknown>>(persistRoute, body);
    },
    onSuccess: async (created) => {
      setError(null);
      const code = readMintedCode(created);
      setMintedCode(code);
      setReleased(true);
      if (persistRoute) {
        await queryClient.invalidateQueries({ queryKey: ['business', persistRoute] });
      }
    },
    onError: (e: Error) => setError(e.message),
  });

  const displayCode = mintedCode ?? (released ? null : null);

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-xs font-medium text-[var(--text-muted)]">{screenId}</p>
          <h2 className="text-xl font-semibold tracking-tight">{title}</h2>
          <p className="mt-1 text-sm text-[var(--text-secondary)]">{description}</p>
          <p className="mt-1 text-xs text-[var(--text-muted)]">{t('wizard.screenType')}</p>
        </div>
        <div className="flex flex-col items-end gap-2">
          {autoCodeHint ? (
            <div className="rounded-md border border-[var(--border-default)] bg-[var(--color-surface)] px-3 py-2 text-right">
              <p className="text-[10px] uppercase tracking-wide text-[var(--text-muted)]">{t('wizard.systemCode')}</p>
              <p className="font-mono text-sm font-medium text-[var(--text-primary)]">
                {displayCode ?? t('wizard.autoGenerated')}
              </p>
              <p className="text-[10px] text-[var(--text-muted)]">{autoCodeHint}</p>
            </div>
          ) : null}
          <Link to={libraryPath} className="text-sm font-medium text-[var(--color-primary)] hover:underline">
            {libraryLabel}
          </Link>
        </div>
      </div>

      <ol className="flex flex-wrap gap-2">
        {steps.map((s, i) => (
          <li key={s.title}>
            <button
              type="button"
              onClick={() => setStep(i)}
              className={`rounded-md px-3 py-1.5 text-xs font-medium ${
                i === step
                  ? 'bg-[var(--color-primary)] text-white'
                  : i < step
                    ? 'bg-[var(--color-surface-hover)] text-[var(--text-primary)]'
                    : 'bg-[var(--color-surface)] text-[var(--text-muted)]'
              }`}
            >
              {i + 1}. {s.title}
            </button>
          </li>
        ))}
      </ol>

      <Card>
        <CardHeader>
          <CardTitle>
            {step + 1}. {current?.title}
          </CardTitle>
          <CardDescription>{current?.hint ?? t('wizard.stepHint')}</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {current?.fields && current.fields.length > 0 ? (
            <div className="grid gap-3 md:grid-cols-2">
              {current.fields.map((f) => (
                <label key={f.key} className="space-y-1 text-sm">
                  <span className="text-[var(--text-secondary)]">{f.label}</span>
                  <Input
                    value={values[f.key] ?? ''}
                    type={f.type === 'number' ? 'number' : f.type === 'date' ? 'date' : 'text'}
                    placeholder={f.placeholder}
                    onChange={(e) => setValues((prev) => ({ ...prev, [f.key]: e.target.value }))}
                  />
                </label>
              ))}
            </div>
          ) : (
            <p className="text-sm text-[var(--text-secondary)]">{t('wizard.bodyHint')}</p>
          )}
          <div className="flex flex-wrap gap-2">
            <Button type="button" variant="secondary" disabled={step === 0 || released} onClick={() => setStep((s) => s - 1)}>
              {t('wizard.back')}
            </Button>
            {!isLast ? (
              <Button type="button" onClick={() => setStep((s) => s + 1)}>
                {t('wizard.next')}
              </Button>
            ) : (
              <Button
                type="button"
                disabled={released || persistMutation.isPending}
                onClick={() => {
                  if (persistRoute && mapBody) {
                    persistMutation.mutate();
                  } else {
                    setReleased(true);
                  }
                }}
              >
                {persistMutation.isPending ? t('saving') : finishLabel}
              </Button>
            )}
            {released ? (
              <Button type="button" variant="secondary" onClick={() => void navigate({ to: libraryPath })}>
                {libraryLabel}
              </Button>
            ) : null}
          </div>
          {error ? <p className="text-sm text-[var(--color-danger)]">{error}</p> : null}
          {released ? (
            <p className="text-sm font-medium text-[var(--color-primary)]">
              {t('wizard.releasedBanner')}
              {displayCode ? ` · ${displayCode}` : ''}
              {persistRoute ? ` — ${t('wizard.inLibrary')}` : ''}
            </p>
          ) : null}
        </CardContent>
      </Card>
    </div>
  );
}
