<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Naswood.Modules.Platform.Application\Naswood.Modules.Platform.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Naswood.BuildingBlocks.AspNetCore\Naswood.BuildingBlocks.AspNetCore.csproj" />
  </ItemGroup>

</Project>
